# Generated by Django 2.2.3 on 2019-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='JobImages/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
